/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "Auth": {
        "region": "eu-central-1",
        "identityPoolId": "eu-central-1:fb1ff7b7-f27e-4ee0-8183-889d89999912",
        "userPoolId": "eu-central-1_PS719oUcl",
        "userPoolWebClientId": "24vlulv9ss7r9mdft67nim943a",
        "oauth": {
            "domain": "cinemasad.auth.eu-central-1.amazoncognito.com"
        }
    },
    "API": {
        "endpoints": [
            {
                "name": "cinema-sad",
                "endpoint": "https://0ptix34dk9.execute-api.eu-central-1.amazonaws.com",
                "region": "eu-central-1"
            }
        ]
    }
};


export default awsmobile;
